using DataCompare.Engine.Reporting;

namespace DataCompare.Engine.Tests.Reporting
{

    /// <summary>
    /// Verifies the HTML generated by DataCompare.Engine.Reporting.DataComparisonHtmlReportWriter,
    /// including section grouping, encoding, and summary counts.
    /// </summary>
    public sealed class DataComparisonHtmlReportWriterTests
    {
        [Fact]
        public void Generate_MixOfDifferingAndIdenticalTables_GroupsIntoBothSections()
        {
            var rows = new[]
            {
                new DataComparisonTableSummary("dbo.Client", 100, 101, 100, 0, 0, 1),
                new DataComparisonTableSummary("dbo.Currency", 5, 5, 5, 0, 0, 0),
            };

            var html = DataComparisonHtmlReportWriter.Generate("server", "Source", "server", "Target", rows);

            Assert.Contains("Tables with differences (<span id=\"differences-count\">1</span>)", html);
            Assert.Contains("Identical tables (<span id=\"identical-count\">1</span>)", html);
            Assert.Contains("dbo.Client", html);
            Assert.Contains("dbo.Currency", html);
        }

        [Fact]
        public void Generate_AllIdentical_OmitsDifferencesSection()
        {
            var rows = new[] { new DataComparisonTableSummary("dbo.Currency", 5, 5, 5, 0, 0, 0) };

            var html = DataComparisonHtmlReportWriter.Generate("server", "Source", "server", "Target", rows);

            Assert.DoesNotContain("Tables with differences", html);
            Assert.Contains("Identical tables (<span id=\"identical-count\">1</span>)", html);
        }

        [Fact]
        public void Generate_NonZeroCounts_MarkedWithNonzeroCssClass()
        {
            var rows = new[] { new DataComparisonTableSummary("dbo.Client", 100, 101, 100, 0, 0, 1) };

            var html = DataComparisonHtmlReportWriter.Generate("server", "Source", "server", "Target", rows);

            Assert.Contains("class=\"nonzero\" data-category=\"missing-source\" data-value=\"1\">1</td>", html);
        }

        [Fact]
        public void Generate_TableNameIsHtmlEncoded()
        {
            var rows = new[] { new DataComparisonTableSummary("dbo.<Weird>", 1, 1, 1, 0, 0, 0) };

            var html = DataComparisonHtmlReportWriter.Generate("server", "Source", "server", "Target", rows);

            Assert.Contains("dbo.&lt;Weird&gt;", html);
            Assert.DoesNotContain("dbo.<Weird>", html);
        }

        [Fact]
        public void Generate_SummaryLine_ReflectsCorrectCounts()
        {
            var rows = new[]
            {
                new DataComparisonTableSummary("dbo.Client", 100, 101, 100, 0, 0, 1),
                new DataComparisonTableSummary("dbo.Currency", 5, 5, 5, 0, 0, 0),
                new DataComparisonTableSummary("dbo.EventLog", 10, 8, 8, 0, 2, 0),
            };

            var html = DataComparisonHtmlReportWriter.Generate("server", "Source", "server", "Target", rows);

            Assert.Contains("Compared 3 table(s) — 2 table(s) with data differences.", html);
        }

        [Fact]
        public void Generate_Header_ShowsSourceAndTargetServerAndDatabase()
        {
            var rows = new[] { new DataComparisonTableSummary("dbo.Currency", 5, 5, 5, 0, 0, 0) };

            var html = DataComparisonHtmlReportWriter.Generate("srcServer", "srcDb", "tgtServer", "tgtDb", rows);

            Assert.Contains("srcServer", html);
            Assert.Contains("srcDb", html);
            Assert.Contains("tgtServer", html);
            Assert.Contains("tgtDb", html);
            Assert.Contains("class=\"side source\"", html);
            Assert.Contains("class=\"side target\"", html);
        }

        [Fact]
        public void Generate_DifferencesSection_IsOpenByDefault_IdenticalSectionIsCollapsed()
        {
            var rows = new[]
            {
                new DataComparisonTableSummary("dbo.Client", 100, 101, 100, 0, 0, 1),
                new DataComparisonTableSummary("dbo.Currency", 5, 5, 5, 0, 0, 0),
            };

            var html = DataComparisonHtmlReportWriter.Generate("server", "Source", "server", "Target", rows);

            Assert.Contains("<details open class=\"differences\">", html);
            Assert.Contains("<details><summary>Identical tables", html);
        }

        [Fact]
        public void Generate_RowWithDetail_RendersDrillDownTree()
        {
            var detail = new DataComparisonDetailNode("dbo.Client: source=100, target=101", [
                new DataComparisonDetailNode("Rows only in Target (1)", [
                    new DataComparisonDetailNode("ClientIdentifier=10351", []),
                ]),
            ]);
            var rows = new[] { new DataComparisonTableSummary("dbo.Client", 100, 101, 100, 0, 0, 1, Detail: detail) };

            var html = DataComparisonHtmlReportWriter.Generate("server", "Source", "server", "Target", rows);

            Assert.Contains("Show row-level detail", html);
            Assert.Contains("Rows only in Target (1)", html);
            Assert.Contains("ClientIdentifier=10351", html);
            // The root node's own summary text shouldn't be duplicated inside the drill-down —
            // it's already shown in the table row itself.
            Assert.DoesNotContain("dbo.Client: source=100, target=101", html);
        }

        [Fact]
        public void Generate_RowWithNoDetail_OmitsDrillDownRow()
        {
            var rows = new[] { new DataComparisonTableSummary("dbo.Client", 100, 101, 100, 0, 0, 1) };

            var html = DataComparisonHtmlReportWriter.Generate("server", "Source", "server", "Target", rows);

            Assert.DoesNotContain("Show row-level detail", html);
            Assert.DoesNotContain("class=\"detail-row\"", html);
        }

        [Fact]
        public void Generate_RowWithReassignedKey_RendersColumnAndCountsAsDiffering()
        {
            var detail = new DataComparisonDetailNode("dbo.Client: source=100, target=100", [
                new DataComparisonDetailNode("Rows with reassigned key (1)", [
                    new DataComparisonDetailNode("Row moved: source key=[Id=1] -> target key=[Id=6]", []),
                ]),
            ]);
            var rows = new[] { new DataComparisonTableSummary("dbo.Client", 100, 100, 99, 0, 0, 0, ReassignedKeyCount: 1, Detail: detail) };

            var html = DataComparisonHtmlReportWriter.Generate("server", "Source", "server", "Target", rows);

            Assert.Contains("<th>Reassigned key</th>", html);
            Assert.Contains("colspan=\"11\"", html);
            Assert.Contains("Tables with differences (<span id=\"differences-count\">1</span>)", html);
            Assert.Contains("Rows with reassigned key (1)", html);
        }

        [Fact]
        public void Generate_RowWithGridColumns_RendersComparisonGridWithKeyAndMatchCells()
        {
            var gridColumns = new[]
            {
                new DataComparisonGridColumn("Id", "1", "6", DataComparisonGridCellKind.ExpectedDifference),
                new DataComparisonGridColumn("Text", "Row 1", "Row 1", DataComparisonGridCellKind.Matched),
            };
            var detail = new DataComparisonDetailNode("dbo.Client: source=100, target=100", [
                new DataComparisonDetailNode("Rows with reassigned key (1)", [
                    new DataComparisonDetailNode(
                        "Row moved: source key=[Id=1] -> target key=[Id=6]", [], GridColumns: gridColumns),
                ]),
            ]);
            var rows = new[] { new DataComparisonTableSummary("dbo.Client", 100, 100, 99, 0, 0, 0, ReassignedKeyCount: 1, Detail: detail) };

            var html = DataComparisonHtmlReportWriter.Generate("server", "Source", "server", "Target", rows);

            Assert.Contains("<table class=\"comparison-grid\">", html);
            Assert.Contains("<td class=\"key-cell\">1</td>", html);
            Assert.Contains("<td class=\"key-cell\">6</td>", html);
            Assert.Contains("<td class=\"match-cell\">Row 1</td>", html);
            // Source's whole column group comes first, then target's — not interleaved and not stacked
            // as separate rows: the source id cell (1) appears before the target id cell (6).
            Assert.True(html.IndexOf("<td class=\"key-cell\">1</td>", StringComparison.Ordinal)
                        < html.IndexOf("<td class=\"key-cell\">6</td>", StringComparison.Ordinal));
        }

        [Fact]
        public void Generate_ChangedRowGridColumns_FlagsChangedColumnAsRealDifference()
        {
            var gridColumns = new[]
            {
                new DataComparisonGridColumn("Id", "4", "4", DataComparisonGridCellKind.Matched),
                new DataComparisonGridColumn("When", "20/08/2026 07:30:00", "20/08/2026 13:00:00", DataComparisonGridCellKind.RealDifference),
            };
            var detail = new DataComparisonDetailNode("dbo.Client: source=100, target=100", [
                new DataComparisonDetailNode("Rows with changed values (1)", [
                    new DataComparisonDetailNode("[Id=4] changed: When", [], GridColumns: gridColumns),
                ]),
            ]);
            var rows = new[] { new DataComparisonTableSummary("dbo.Client", 100, 100, 99, 1, 0, 0, Detail: detail) };

            var html = DataComparisonHtmlReportWriter.Generate("server", "Source", "server", "Target", rows);

            Assert.Contains("<td class=\"match-cell\">4</td>", html);
            Assert.Contains("<td class=\"diff-cell\">20/08/2026 07:30:00</td>", html);
            Assert.Contains("<td class=\"diff-cell\">20/08/2026 13:00:00</td>", html);
        }

        [Fact]
        public void Generate_RowOnlyInSourceGridColumns_ShowsSourceValuesAndEmptyTargetCells()
        {
            var gridColumns = new[]
            {
                new DataComparisonGridColumn("ID", "5418", string.Empty, DataComparisonGridCellKind.RealDifference),
                new DataComparisonGridColumn("Description", "testing charge", string.Empty, DataComparisonGridCellKind.RealDifference),
            };
            var detail = new DataComparisonDetailNode("dbo.Client: source=100, target=99", [
                new DataComparisonDetailNode("Rows only in Source (1)", [
                    new DataComparisonDetailNode("ID=5418, Description=testing charge", [], GridColumns: gridColumns),
                ]),
            ]);
            var rows = new[] { new DataComparisonTableSummary("dbo.Client", 100, 99, 99, 0, 1, 0, Detail: detail) };

            var html = DataComparisonHtmlReportWriter.Generate("server", "Source", "server", "Target", rows);

            Assert.Contains("<td class=\"diff-cell\">5418</td>", html);
            Assert.Contains("<td class=\"diff-cell\">testing charge</td>", html);
            // The target side has no row at all — its cells render empty, not missing.
            Assert.Contains("<td class=\"diff-cell\"></td>", html);
        }

        [Fact]
        public void Generate_CategoryTaggedExample_RendersAcceptButtonsWithMatchingRowIdAndCategorySlug()
        {
            var gridColumns = new[] { new DataComparisonGridColumn("When", "07:30:00", "13:00:00", DataComparisonGridCellKind.RealDifference) };
            var detail = new DataComparisonDetailNode("dbo.Client: source=100, target=100", [
                new DataComparisonDetailNode(
                    "Rows with changed values (1)",
                    [new DataComparisonDetailNode("[Id=4] changed: When", [], GridColumns: gridColumns)],
                    Category: DataComparisonRowCategory.Changed),
            ]);
            var rows = new[] { new DataComparisonTableSummary("dbo.Client", 100, 100, 99, 1, 0, 0, Detail: detail) };

            var html = DataComparisonHtmlReportWriter.Generate("server", "Source", "server", "Target", rows);

            Assert.Contains("id=\"row-0\"", html);
            Assert.Contains("id=\"row-0-detail\"", html);
            Assert.Contains("onclick=\"acceptOne(this, 'row-0', 'changed')\"", html);
            Assert.Contains("onclick=\"acceptAllInTable('row-0')\"", html);
            Assert.Contains("<th>Accepted</th>", html);
        }

        [Fact]
        public void Generate_IdenticalTable_GetsNoRowIdOrAcceptButtons()
        {
            var rows = new[] { new DataComparisonTableSummary("dbo.Currency", 5, 5, 5, 0, 0, 0) };

            var html = DataComparisonHtmlReportWriter.Generate("server", "Source", "server", "Target", rows);

            Assert.DoesNotContain("id=\"row-", html);
            Assert.DoesNotContain("onclick=\"acceptOne(", html);
            Assert.DoesNotContain("onclick=\"acceptAllInTable(", html);
        }

        [Fact]
        public void Generate_RowWithDifferences_RendersPercentDiffersColumn()
        {
            // 100 source rows, 10 changed — 10% differs.
            var rows = new[] { new DataComparisonTableSummary("dbo.Client", 100, 100, 90, 10, 0, 0) };

            var html = DataComparisonHtmlReportWriter.Generate("server", "Source", "server", "Target", rows);

            Assert.Contains("<th>% Differs</th>", html);
            Assert.Contains("<td>10.0%</td>", html);
        }
    }
}
