using DataCompare.Engine.Reporting;
using DataCompare.Engine.Schema;

namespace DataCompare.Engine.Tests.Reporting
{

    /// <summary>
    /// Verifies the HTML generated by DataCompare.Engine.Reporting.SchemaHtmlReportWriter, including
    /// section grouping, highlighting of changed columns, and encoding.
    /// </summary>
    public sealed class SchemaHtmlReportWriterTests
    {
        /// <summary>
        /// creates a single-column DataCompare.Engine.Schema.ColumnSchema object for use in test tables.
        /// </summary>
        /// <param name="name">a System.String object giving the column name</param>
        /// <param name="dataType">a System.String object giving the SQL data type of the column</param>
        /// <returns>returns a DataCompare.Engine.Schema.ColumnSchema object</returns>
        private static ColumnSchema Column(string name, string dataType = "int") =>
            new(name, dataType, 0, 0, 0, IsNullable: true, IsIdentity: false, IsPrimaryKey: false);

        /// <summary>
        /// creates a DataCompare.Engine.Schema.TableSchema object in the dbo schema with the given
        /// name and columns.
        /// </summary>
        /// <param name="name">a System.String object giving the table name</param>
        /// <param name="columns">a System.Array object where T is a DataCompare.Engine.Schema.ColumnSchema object, giving the table's columns</param>
        /// <returns>returns a DataCompare.Engine.Schema.TableSchema object</returns>
        private static TableSchema Table(string name, params ColumnSchema[] columns) => new("dbo", name, columns);

        [Fact]
        public void Generate_ProducesValidHtmlDocumentWithSourceAndTargetLabels()
        {
            var table = Table("Widgets", Column("Id"));
            var source = new DatabaseSchema([table]);
            var target = new DatabaseSchema([table]);
            var result = new SchemaComparer().Compare(source, target);

            var html = SchemaHtmlReportWriter.GenerateTablesAndViews("srv-a", "AppDb", "srv-b", "AppDb", result, source, target);

            Assert.StartsWith("<!DOCTYPE html>", html);
            Assert.Contains("srv-a", html);
            Assert.Contains("srv-b", html);
            Assert.Contains("</html>", html);
            // Same source/target banner (grey Source panel + DB icon, orange Target panel + DB icon) as
            // the data comparison report, not the older plain "Source"/"Target" tag pills.
            Assert.Contains("<div class=\"banner\">", html);
            Assert.Contains("class=\"side source\"", html);
            Assert.Contains("class=\"side target\"", html);
            Assert.Contains("class=\"db-icon\"", html);
        }

        [Fact]
        public void GenerateSummary_TableOnlyInSourceAndOneChangedTable_RendersDifferencePercentagesLine()
        {
            var orphanTable = Table("Orphan", Column("Id"));
            var changedInSource = Table("Widgets", Column("Amount", "int"));
            var changedInTarget = Table("Widgets", Column("Amount", "bigint"));
            var unchanged = Table("Currency", Column("Id"));
            var source = new DatabaseSchema([orphanTable, changedInSource, unchanged]);
            var target = new DatabaseSchema([changedInTarget, unchanged]);
            var result = new SchemaComparer().Compare(source, target);

            var html = SchemaHtmlReportWriter.GenerateSummary("srv-a", "AppDb", "srv-b", "AppDb", result, source, target);

            // 1 only-in-source table over 3 total tables (union) = 33.3%; 1 changed table over 2 common
            // tables (Widgets, Currency) = 50.0%.
            Assert.Contains("Table difference: 33.3% — Schema difference: 50.0%", html);
        }

        [Fact]
        public void Generate_TableOnlyInSource_AppearsUnderOnlyInSourceSection()
        {
            var sourceOnlyTable = Table("Orphan", Column("Id"));
            var source = new DatabaseSchema([sourceOnlyTable]);
            var target = new DatabaseSchema([]);
            var result = new SchemaComparer().Compare(source, target);

            var html = SchemaHtmlReportWriter.GenerateTablesAndViews("A", "A-db", "B", "B-db", result, source, target);

            Assert.Contains("Only in Source (1)", html);
            Assert.Contains("Orphan", html);
        }

        [Fact]
        public void Generate_ChangedColumn_HighlightsTheDifferingLine()
        {
            var source = new DatabaseSchema([Table("Widgets", Column("Amount", "int"))]);
            var target = new DatabaseSchema([Table("Widgets", Column("Amount", "bigint"))]);
            var result = new SchemaComparer().Compare(source, target);

            var html = SchemaHtmlReportWriter.GenerateTablesAndViews("A", "A-db", "B", "B-db", result, source, target);

            Assert.Contains("Different (1)", html);
            Assert.Contains("class=\"hl\"", html);
        }

        [Fact]
        public void Generate_IdenticalTables_StillIncludedWithFullDdl()
        {
            var table = Table("Widgets", Column("Id"), Column("Name", "nvarchar"));
            var source = new DatabaseSchema([table]);
            var target = new DatabaseSchema([table]);
            var result = new SchemaComparer().Compare(source, target);

            var html = SchemaHtmlReportWriter.GenerateTablesAndViews("A", "A-db", "B", "B-db", result, source, target);

            Assert.Contains("Identical (1)", html);
            Assert.Contains("CREATE TABLE", html);
            Assert.Contains("[Name]", html);
        }

        [Fact]
        public void Generate_EscapesHtmlSpecialCharactersInNames()
        {
            var table = Table("Weird<Name>", Column("Id"));
            var source = new DatabaseSchema([table]);
            var target = new DatabaseSchema([]);
            var result = new SchemaComparer().Compare(source, target);

            var html = SchemaHtmlReportWriter.GenerateTablesAndViews("A", "A-db", "B", "B-db", result, source, target);

            Assert.DoesNotContain("Weird<Name>", html);
            Assert.Contains("Weird&lt;Name&gt;", html);
        }

        [Fact]
        public void GenerateSummary_RendersObjectTypeBreakdownTable()
        {
            var source = new DatabaseSchema([Table("Widgets", Column("Id"))]);
            var target = new DatabaseSchema([]);
            var result = new SchemaComparer().Compare(source, target);

            var html = SchemaHtmlReportWriter.GenerateSummary("A", "A-db", "B", "B-db", result, source, target);

            Assert.Contains("table.object-type-summary", html);
            Assert.Contains("Tables</td>", html);
            Assert.DoesNotContain("Functions</td>", html);
        }

        [Fact]
        public void GenerateRoutines_RoutineOnlyInSource_AppearsUnderOnlyInSourceSection()
        {
            var routine = new RoutineSchema("dbo", "OldCleanupJob", ModifiedAt: default, Definition: "AS SELECT 1", Kind: RoutineKind.StoredProcedure);
            var source = new DatabaseSchema([]) { Routines = [routine] };
            var target = new DatabaseSchema([]) { Routines = [] };
            var result = new SchemaComparer().Compare(source, target);

            var html = SchemaHtmlReportWriter.GenerateRoutines("A", "A-db", "B", "B-db", result, source, target);

            Assert.Contains("Only in Source (1)", html);
            Assert.Contains("OldCleanupJob", html);
            Assert.Contains("PROCEDURE", html);
        }
    }
}
